#!/usr/bin/env python

from argparse import ArgumentParser
import fnmatch

line_filter = ['#define MAVLINK_MSG_ID_FMU_TM_CRC']

# Start
if __name__ == '__main__':
    parser = ArgumentParser(description="This script overwrites EXTRA_CRC of custom Kaiken message in autogenerated C lib")
    parser.add_argument("-d", dest="destination", help="destination path", required=True)
    args = parser.parse_args()

    filename = f'{args.destination}/mavlink_msg_fmu_tm.h'

    # Read in the file
    with open(filename, 'r') as file:
        lines = file.readlines()
        for line in lines:
            for lf in line_filter:
                if fnmatch.fnmatch(line, f'{lf} *'):
                    lines[lines.index(line)] = f"{lf} 0\n"

    # Write the file out again
    with open(filename, 'w') as file:
        file.writelines(lines)
        file.close()
