#!/usr/bin/env python

from argparse import ArgumentParser
import fnmatch
import sys

# Start
if __name__ == '__main__':
    parser = ArgumentParser(description="This script overwrites EXTRA_CRC of custom Kaiken message in autogenerated Python lib")
    parser.add_argument("-d", dest="destination", help="destination path of kaiken.py", required=True)
    args = parser.parse_args()

    # Read in the file
    filename = f'{args.destination}/kaiken.py'
    try:
        file = open(filename, 'r')
    except OSError:
        print("Could not open/read file:", filename)
        sys.exit()

    lines = file.readlines()
    for line in lines:
        if fnmatch.fnmatch(line, 'class MAVLink_fmu_tm_message(MAVLink_message):*'):
            for i in range(lines.index(line), len(lines)):
                if fnmatch.fnmatch(lines[i], '*crc_extra = *'):
                    lines[i] = "    crc_extra = 0\n"
                    break
            break

    # Write the file out again
    with open(filename, 'w') as file:
        file.writelines(lines)
        file.close()
