#!/usr/bin/env python

from argparse import ArgumentParser
import fnmatch
import sys

# Start
if __name__ == '__main__':
    parser = ArgumentParser(description="This script overwrites EXTRA_CRC of custom Kaiken message in autogenerated Python lib")
    parser.add_argument("-d", dest="destination", help="destination path of kaiken.py", required=True)
    args = parser.parse_args()

    # Read in the file
    filename = f'{args.destination}/mavutil.py'
    try:
        file = open(filename, 'r')
    except OSError:
        print("Could not open/read file:", filename)
        sys.exit()

    lines = file.readlines()
    for line in lines:
        if fnmatch.fnmatch(line, '*mavlink.MAV_TYPE_VTOL_DUOROTOR*'):
            lines[lines.index(line)] = f"# {line}\n"
        if fnmatch.fnmatch(line, '*mavlink.MAV_TYPE_VTOL_QUADROTOR*'):
            lines[lines.index(line)] = f"# {line}\n"

    # Write the file out again
    with open(filename, 'w') as file:
        file.writelines(lines)
        file.close()
